### ISSUE TITLE
PR status

### ISSUE THREAD

**Issue by rkdarst** [jupyterhub/batchspawner#183]
Since our PRs are so stagnent, I made a summary of them below to hopefully help maintainers decide what to do.   Or maybe encourage more people to take a look.

Six should be used right away, some are old.  At least three can be closed.

- [ ] #180 (fix CI) Can be used immediately.
- [ ] #179 (unknown job status) some comments but can then be used.  Needs changelog entry.
- [ ] #178 duplicate of #179, #179 should be used instead.  Close when #179 accepted.
- [ ] #177 (job script set -e) - makes sense, someone either needs to do it and accept some people's use cases will change, or accept that we can never change it.  Needs changelog entry.
- [ ] #170 (slurm --gres option) Should be accepted if we want more options, instead of the generic req_options.  Needs changelog entry, I already added one but it is out of date since the release.
- [ ] #165 Can be used, I have a local changelog entry I couldn't push, but of course have to update since it's so old, and there has been a release.
- [ ] #137 (fix grid engine) can probably be used.  more importantly, we should do some community building to bring these contributors in.
- [ ] #136 (OAR) I would probably reject this, since the OAR scheduler seems sort of insecure, and make it some sort of community recipe.  We can help people do it, but shouldn't make it easy to do insecure things out of the box.
- [ ] #119 (environment refactoring) This was a draft test of mine, no point to work on it until we have a way to accept new ideas.
- [ ] #114 Now a bit obsolete, with select port on remote side.  Needs later thought, after we have a way to accept new ideas.
- [ ] #75 (sigterm before sigkill) Not really needed with slurm, but could be useful other ways.  Not something to think about, until we have solved the general PR problem.

**Comment by rkdarst** [comment]
My first submission seemed to fail, so I tried again.  But it actually worked.  Closing this, someone can delete if possible.
